---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app flux-webhooks-laneth
  namespace: flux-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  interval: 1h
  path: ./kubernetes/apps/flux-system/addons/webhooks
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: laneth-kubernetes
  targetNamespace: flux-system
  timeout: 3m
