---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app flux-webhooks-laneth
  namespace: flux-system
spec:
  targetNamespace: flux-system
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/apps/flux-system/addons/webhooks
  prune: true
  sourceRef:
    kind: GitRepository
    name: laneth-kubernetes
  wait: true
  interval: 15m
  retryInterval: 1m
  timeout: 3m
