---
fail_fast: false
repos:
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.26.3
    hooks:
      - args:
          - --config-file
          - .github/linters/.yamllint.yaml
        id: yamllint
        exclude: ^(ansible/manifests/|.*dashboard.json)
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.3.0
    hooks:
      - id: remove-crlf
      - id: remove-tabs
  - repo: https://github.com/sirosen/texthooks
    rev: 0.3.1
    hooks:
      - id: fix-smartquotes
        exclude: ^ansible/manifests/
      - id: fix-ligatures
        exclude: ^ansible/manifests/
  - repo: https://github.com/k8s-at-home/sops-pre-commit
    rev: v2.1.1
    hooks:
      - id: forbid-secrets
  - repo: https://github.com/gitguardian/gg-shield
    rev: v1.12.0
    hooks:
      - id: ggshield
        language_version: python3
        stages: [commit]
