---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

vars:
  KUBERNETES_DIR: "{{.ROOT_DIR}}/kubernetes"

env:
  KUBECONFIG: "{{.ROOT_DIR}}/kubeconfig"
  SOPS_AGE_KEY_FILE: '{{.ROOT_DIR}}/age.key'

includes:
  bootstrap: .taskfiles/bootstrap/Taskfile.yaml
  flux: .taskfiles/Flux/Taskfile.yaml
  kubernetes:
    aliases: ["k8s", "ku"]
    taskfile: .taskfiles/Kubernetes/Taskfile.yaml

tasks:

  default:
    silent: true
    cmd: task -l
