---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prowlarr-config-v5
  namespace: downloads
  labels:
    app.kubernetes.io/instance: &name prowlarr
    app.kubernetes.io/name: *name
    snapshot.home.arpa/enabled: "true"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ceph-block
