---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prowlarr-config-v4
  namespace: downloads
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: zfs-block
