---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prowlarr-config-v4
  namespace: downloads
  labels:
    app.kubernetes.io/instance: &name prowlarr
    app.kubernetes.io/name: *name
    pmb.home.arpa/snapshot: "true"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: zfs-block
