---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app prowlarr
  namespace: downloads
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.2.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    image:
      repository: ghcr.io/onedr0p/prowlarr-nightly
      tag: 1.2.0.2569@sha256:83e191cfc4851fbf4dfc962d22b21de7b669118b6a45562b265decbdcfc7e5be
    controller:
      labels:
        setGateway: "true"
    env:
      TZ: ${TIMEZONE}
      PROWLARR__INSTANCE_NAME: Prowlarr
      PROWLARR__PORT: &port 80
      PROWLARR__LOG_LEVEL: info
    service:
      main:
        ports:
          http:
            port: *port
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: "cloud-search"
        hosts:
          - host: &host prowlarr.${SECRET_PUBLIC_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    podSecurityContext:
      runAsUser: 2000
      runAsGroup: 2000
      fsGroup: 2000
      fsGroupChangePolicy: OnRootMismatch
    persistence:
      config:
        enabled: true
        existingClaim: prowlarr-config-v5
      backup:
        enabled: true
        type: nfs
        server: ${SECRET_BACKUP_SERVER}
        path: ${SECRET_BACKUP_FOLDER}/prowlarr
        mountPath: /config/Backups
        readOnly: false
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        memory: 500Mi
