---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prowlarr
  namespace: downloads
spec:
  interval: 15m
  chart:
    spec:
      chart: prowlarr
      version: 4.5.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system

  values:
    image:
      repository: ghcr.io/k8s-at-home/prowlarr-nightly
      tag: v0.4.7.1978
    controller:
      labels:
        pmb.home.arpa/snapshot-claim: &claimName "prowlarr-config-v5"
        setGateway: "true"
    env:
      TZ: ${TIMEZONE}
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: "cloud-search"
        hosts:
          - host: &host prowlarr.${SECRET_INTERNAL_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    securityContext:
      runAsUser: 2000
      runAsGroup: 2000
    podAnnotations:
      backup.velero.io/backup-volumes: config
    persistence:
      config:
        enabled: true
        existingClaim: *claimName
      backup:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: ${SECRET_BACKUP_SERVER}
            path: ${SECRET_BACKUP_FOLDER}/prowlarr
        mountPath: /config/Backups
        readOnly: false
    resources:
      requests:
        memory: 100Mi
        cpu: 100m
      limits:
        memory: 500Mi
