---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prowlarr
  namespace: downloads
spec:
  interval: 15m
  chart:
    spec:
      chart: prowlarr
      version: 4.4.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system

  values:
    image:
      repository: ghcr.io/k8s-at-home/prowlarr-nightly
      tag: v0.4.0.1823
    env:
      TZ: ${CONFIG_TIMEZONE}
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: "cloud-search"
        hosts:
          - host: &host "prowlarr.${SECRET_INTERNAL_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    securityContext:
      runAsUser: 2000
      runAsGroup: 2000
    podAnnotations:
      backup.velero.io/backup-volumes: config
    persistence:
      config:
        enabled: true
        existingClaim: prowlarr-config-v4
      backup:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "${SECRET_BACKUP_SERVER}"
            path: /backup/data/app/prowlarr
        mountPath: /config/Backups
        readOnly: false
    resources:
      requests:
        memory: 100Mi
        cpu: 100m
      limits:
        memory: 500Mi
