---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

tasks:

  reconcile:
    desc: Force update Flux to pull in changes from your Git repository
    cmd: flux reconcile --namespace flux-system kustomization cluster --with-source

  monitor:
    desc: Monitor the progress of Kustomizations and Helm Releases
    cmd: watch "flux get kustomizations|grep -v Applied;flux get helmrelease -A|grep -v succeeded"
