# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-secret-laneth
stringData:
    token: ENC[AES256_GCM,data:pUI5QQo6VZ8iQ9jZRcokhV1Ap9KFlQBBr8QR5xNj8rA=,iv:uGQzCnQGfYkLdAgiSb7QTRa0tDwprTnVqZgPaZYOVCQ=,tag:XjwhUKbmARJYeGgoiqrwcA==,type:str]
sops:
    age:
        - recipient: age1ukc0wt99g0jw038mzrx5g5r4cj7298mx3hdf2g9kqvtcme7vz5jsj0lxeq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUTHkrcW02V1J1ZTAzV1RK
            bllkdWJFNHkvb0d5UE1KM2MvN2hSOVFHMlQ4CkM3NGtzajM5Z0hHZ3p4UkQvUldT
            QnRJMUdYSnU5VURGblJtL2VFYmNpWU0KLS0tIFE1T1hPeDBZc0VLQkdwbFZoVytI
            Q3lxemZITGhDbWhvSmRDOXR1SE1OSTgKy9KmsPSlci/S+eYsDE+Cmq9C5yNoUoUj
            fKcC4EhuBCIUYxms36pK3B62xqtXPYbDCbv+gdJWZ29WFXRkGehRTg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-09T20:14:36Z"
    mac: ENC[AES256_GCM,data:P2tr+8qg8SlNF9LhibAkNrFZ+iH+6SO5M6el+LcvK+g9hazQPthf6eht/HXaZo/nxT/BAVdPcgLgNVFB1ZGDaIlvYTQJy/VfiXNQfjCJ3gCSKdqU30bjsF6khAqUkj5aBVk6nOqkB9mCWBpXwNIZphVe76DzpnIv2QArPSsx+z0=,iv:XusiRTIcHag8IGYvbhZ/5T8twtfuKyDi4dSunDyJn9o=,tag:0VqNw2/DOBqxaeFu4LtEUA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
