---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hello-world
  namespace: default
  labels:
    app.kubernetes.io/name: hello-kubernetes
    app.kubernetes.io/instance: hello-world
    app.kubernetes.io/version: "1.10"
