---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Pre Flux-Kustomizations
  - ./namespace.yaml
  # - ./policy.yaml
  # Flux-Kustomizations
  - ./bazarr/ks.yaml
  - ./flaresolverr/ks.yaml
  - ./jellyseerr/ks.yaml
  - ./prowlarr/ks.yaml
  - ./radarr/ks.yaml
  - ./sonarr/ks.yaml
  - ./unpackerr/ks.yaml
