---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: laneth-cluster
  namespace: flux-system
spec:
  interval: 10m
  ref:
    branch: main
  url: https://github.com/laneth42/homelab.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: laneth-cluster
  namespace: flux-system
spec:
  interval: 10m
  path: ./cluster/flux
  prune: true
  wait: false
  sourceRef:
    kind: GitRepository
    name: laneth-cluster
