---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: &app recyclarr
  namespace: downloads
spec:
  schedule: "0 3 * * *"
  # the gateway sidecar gets stuck, blocking future runs - this is a workaround.
  concurrencyPolicy: Replace
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      backoffLimit: 3
      ttlSecondsAfterFinished: 300
      template:
        metadata:
          labels:
            setGateway: "true"
        spec:
          automountServiceAccountToken: false
          restartPolicy: OnFailure
          initContainers:
            - name: render-config
              image: ghcr.io/onedr0p/recyclarr:3.0.0@sha256:15ac3b69ea9fe66ab2b03f5f3daff36d188a6f2f81a894f64707079ef76989aa
              envFrom:
                - secretRef:
                    name: *app
              command:
                - "/bin/bash"
                - -c
              args:
                - "envsubst < /config/recyclarr.yaml > /shared/recyclarr.yaml"
              volumeMounts:
                - name: config
                  mountPath: /config
                - name: shared
                  mountPath: /shared
          containers:
            - name: sonarr
              image: ghcr.io/onedr0p/recyclarr:3.0.0@sha256:15ac3b69ea9fe66ab2b03f5f3daff36d188a6f2f81a894f64707079ef76989aa
              env:
                - name: TZ
                  value: ${TIMEZONE}
                - name: RECYCLARR_APP_DATA
                  value: /config
              command:
                - /app/recyclarr
              args:
                - sonarr
                - --config
                - /config/recyclarr.yaml
              volumeMounts:
                - name: shared
                  mountPath: /config/recyclarr.yaml
                  subPath: recyclarr.yaml
                  readOnly: true
            - name: radarr
              image: ghcr.io/onedr0p/recyclarr:3.0.0@sha256:15ac3b69ea9fe66ab2b03f5f3daff36d188a6f2f81a894f64707079ef76989aa
              env:
                - name: TZ
                  value: ${TIMEZONE}
                - name: RECYCLARR_APP_DATA
                  value: /config
              command:
                - /app/recyclarr
              args:
                - radarr
                - --config
                - /config/recyclarr.yaml
              volumeMounts:
                - name: shared
                  mountPath: /config/recyclarr.yaml
                  subPath: recyclarr.yaml
                  readOnly: true
          volumes:
            - name: config
              configMap:
                name: *app
            - name: shared
              emptyDir: {}
