---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: &app recyclarr
  namespace: downloads
spec:
  schedule: "0 3 * * *"
  concurrencyPolicy: "Forbid"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      backoffLimit: 3
      ttlSecondsAfterFinished: 300
      template:
        spec:
          automountServiceAccountToken: false
          restartPolicy: OnFailure
          initContainers:
            - name: render-config
              image: ghcr.io/k8s-at-home/recyclarr:v2.2.1
              envFrom:
                - secretRef:
                    name: *app
              command:
                - "/bin/bash"
                - -c
              args:
                - "envsubst < /config/recyclarr.yaml > /shared/recyclarr.yaml"
              volumeMounts:
                - name: config
                  mountPath: /config
                - name: shared
                  mountPath: /shared
          containers:
            - name: sonarr
              image: ghcr.io/k8s-at-home/recyclarr:v2.2.1
              imagePullPolicy: IfNotPresent
              env:
                - name: TZ
                  value: ${CONFIG_TIMEZONE}
                - name: RECYCLARR_APP_DATA
                  value: /config
              command:
                - /app/recyclarr
              args:
                - sonarr
                - --config
                - /config/recyclarr.yaml
              volumeMounts:
                - name: shared
                  mountPath: /config/recyclarr.yaml
                  subPath: recyclarr.yaml
                  readOnly: true
            - name: radarr
              image: ghcr.io/k8s-at-home/recyclarr:v2.2.1
              imagePullPolicy: IfNotPresent
              env:
                - name: TZ
                  value: ${CONFIG_TIMEZONE}
                - name: RECYCLARR_APP_DATA
                  value: /config
              command:
                - /app/recyclarr
              args:
                - radarr
                - --config
                - /config/recyclarr.yaml
              volumeMounts:
                - name: shared
                  mountPath: /config/recyclarr.yaml
                  subPath: recyclarr.yaml
                  readOnly: true
          volumes:
            - name: config
              configMap:
                name: *app
            - name: shared
              emptyDir: {}
