---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: &app recyclarr
  namespace: downloads
spec:
  schedule: "0 3 * * *"
  # the gateway sidecar gets stuck, blocking future runs - this is a workaround.
  concurrencyPolicy: Replace
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      backoffLimit: 3
      ttlSecondsAfterFinished: 86400
      template:
        metadata:
          labels:
            setGateway: "true"
        spec:
          automountServiceAccountToken: false
          restartPolicy: OnFailure
          initContainers:
            - name: render-configs
              image: ghcr.io/onedr0p/alpine:3.17.0
              envFrom:
                - secretRef:
                    name: *app
              command:
                - "/bin/bash"
                - -c
              args:
                - "envsubst < /config/recyclarr.yml > /shared/recyclarr.yml"
              volumeMounts:
                - name: config
                  mountPath: /config
                - name: shared
                  mountPath: /shared
          containers:
            - name: sonarrs
              image: ghcr.io/recyclarr/recyclarr:4.2.0
              env:
                - name: TZ
                  value: ${TIMEZONE}
              command:
                - /app/recyclarr/recyclarr
              args:
                - sonarr
              volumeMounts:
                - name: shared
                  mountPath: /config/recyclarr.yml
                  subPath: recyclarr.yml
                  readOnly: true
            - name: radarrs
              image: ghcr.io/recyclarr/recyclarr:4.2.0
              env:
                - name: TZ
                  value: ${TIMEZONE}
              command:
                - /app/recyclarr/recyclarr
              args:
                - radarr
              volumeMounts:
                - name: shared
                  mountPath: /config/recyclarr.yml
                  subPath: recyclarr.yml
                  readOnly: true
          volumes:
            - name: config
              configMap:
                name: *app
            - name: shared
              emptyDir: {}
