---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
  - ./dashboard
  - ./config-pvc.yaml
  - ./volsync.yaml
labels:
  - pairs:
      app.kubernetes.io/name: sonarr
      app.kubernetes.io/instance: sonarr
