---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app unpackerr
  namespace: downloads
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 0.2.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    image:
      repository: ghcr.io/onedr0p/unpackerr
      tag: 0.10.1@sha256:7b6139ff714deec672b2627a61e5b6ac4d75584cf8dec71250ac8c4d5fda51d3
    env:
      TZ: ${TIMEZONE}
      UN_SONARR_0_URL: http://sonarr
      UN_SONARR_0_PATHS_0: /media/requests/complete
      UN_RADARR_0_URL: http://radarr
      UN_RADARR_0_PATHS_0: /media/requests/complete
    envFrom:
      - secretRef:
          name: *app
    service:
      main:
        enabled: false
    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
      startup:
        enabled: false
    podSecurityContext:
      runAsUser: 2000
      runAsGroup: 2000
      fsGroup: 2000
      fsGroupChangePolicy: OnRootMismatch
    persistence:
      complete:
        enabled: true
        type: nfs
        server: "${SECRET_MEDIA_SERVER}"
        path: /media/requests/complete
        mountPath: /media/requests/complete
    podAnnotations:
      secret.reloader.stakater.com/reload: unpackerr
    resources:
      requests:
        cpu: 100m
        memory: 250Mi
      limits:
        memory: 1000Mi
