---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: unpackerr
  namespace: downloads
spec:
  interval: 15m
  chart:
    spec:
      chart: unpackerr
      version: 5.3.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
  values:
    image:
      repository: docker.io/golift/unpackerr
      tag: 0.10.0
    env:
      TZ: ${CONFIG_TIMEZONE}
      UN_SONARR_0_URL: http://sonarr:8989
      UN_RADARR_0_URL: http://radarr:7878

    envFrom:
      - secretRef:
          name: unpackerr
    securityContext:
      runAsUser: 2000
      runAsGroup: 2000
    persistence:
      config:
        enabled: false
      complete:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "${SECRET_MEDIA_SERVER}"
            path: /media/requests/complete
        mountPath: /media/requests/complete
    resources:
      requests:
        cpu: 100m
        memory: 250Mi
      limits:
        memory: 1000Mi
