---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app unpackerr
  namespace: downloads
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.3.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controller:
      annotations:
        reloader.stakater.com/auto: "true"
      labels:
        setGateway: "true"
    image:
      repository: ghcr.io/onedr0p/unpackerr
      tag: 0.11.1@sha256:8aa2e192f27fe2f6c22b4c73ec780507f2b26cfed26d4c906b1852f53a18d27d
    env:
      TZ: ${TIMEZONE}
      UN_SONARR_0_URL: http://sonarr
      UN_SONARR_0_PATHS_0: /media/requests/complete
      UN_RADARR_0_URL: http://radarr
      UN_RADARR_0_PATHS_0: /media/requests/complete
    envFrom:
      - secretRef:
          name: *app
    service:
      main:
        enabled: false
    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
      startup:
        enabled: false
    podSecurityContext:
      runAsUser: 2000
      runAsGroup: 2000
      fsGroup: 2000
      fsGroupChangePolicy: OnRootMismatch
    persistence:
      complete:
        enabled: true
        type: nfs
        server: "${SECRET_MEDIA_SERVER}"
        path: /media/requests/complete
        mountPath: /media/requests/complete
    resources:
      requests:
        cpu: 10m
        memory: 250Mi
      limits:
        memory: 2000Mi
