---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: laneth-apps
  namespace: flux-system
spec:
  interval: 10m
  path: ./cluster/apps
  prune: true
  sourceRef:
    kind: GitRepository
    name: laneth-cluster
  dependsOn:
    - name: core
  decryption:
    provider: sops
    secretRef:
      name: sops-age-laneth
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
      - kind: Secret
        name: cluster-secrets
      - kind: Secret
        name: laneth-secrets
