---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/source.toolkit.fluxcd.io/gitrepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: laneth-kubernetes
  namespace: flux-system
spec:
  interval: 30m
  url: https://github.com/laneth42/homelab.git
  ref:
    branch: main
  ignore: |
    # exclude all
    /*
    # include kubernetes directory
    !/kubernetes
---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: laneth-kubernetes
  namespace: flux-system
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-age-laneth
  interval: 1h
  path: ./kubernetes/flux
  prune: true
  postBuild:
    substituteFrom:
      - name: cluster-settings
        kind: ConfigMap
        optional: false
      - name: cluster-secrets
        kind: Secret
        optional: false
      - name: laneth-secrets
        kind: Secret
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: laneth-kubernetes
  timeout: 5m
  wait: false
