# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: laneth-secrets
    namespace: flux-system
stringData:
    TIMEZONE: ENC[AES256_GCM,data:9f63EXfvVLv3WvUHKFey,iv:TLdn160hgKAuiBtY2c2M1jdaRWmseApQZ5qevXkfzGE=,tag:RFGAUfWGzyfPL4QTo5ZEYQ==,type:str]
    SECRET_PUBLIC_DOMAIN: ENC[AES256_GCM,data:43W4du0qsrMUAOZZ,iv:rXMzJ1irUf7GPyCgwQ2G5PXeLL+ynOEccWxl758zq2w=,tag:pjLLW5V64hGBknbv8KD6fA==,type:str]
    SECRET_PRIVATE_DOMAIN: ENC[AES256_GCM,data:uQn4q/h6BG8erEHp,iv:UzMDbnPmLpyC3mfpMi0DGD1QWo3J4PWZQyN1aW2Ej7Y=,tag:YqXh7aN+ayNkb0XBxnsg2g==,type:str]
    SECRET_VPN_HOST: ENC[AES256_GCM,data:IGDNH8PlobOt5UClqh9aZCg=,iv:FDBF72E5fMg5xzxSpsSIRRUltpVQAYt1h+CHRRp+oTc=,tag:JVYARtF+qFDiWvXPliYpxw==,type:str]
    SECRET_VPN_IP: ENC[AES256_GCM,data:L3Gq01PjX8rwFwoxNjQ=,iv:N25493IRRqW4FaRC2Pi3Z3ZeDGRN1MeOL89tKhaKOpY=,tag:MgRjf5Hv8qncky+cYtthKQ==,type:str]
    SECRET_BACKUP_SERVER: ENC[AES256_GCM,data:f+8BD2mOXk6pmgKaWc6jAvFJuJ01WA==,iv:aIBm8TlyvtVC95Jh7DNODIV9wVDA3iXG5qil+c1nkzU=,tag:06gGZmN9SVmRdz+K0HyRPg==,type:str]
    SECRET_BACKUP_FOLDER: ENC[AES256_GCM,data:4jvWi3NzBqnqPs+Q0XoOrA==,iv:xxxRxdey3yLzoYRJazVK8Z7urHm1rTSbsiObVI1Bnmk=,tag:sRgmB0507hJTqYHG+pZRmA==,type:str]
    SECRET_MEDIA_SERVER: ENC[AES256_GCM,data:1G5LY/meFdL7KIuhFLz/dittgnEQEQ==,iv:B1nYDEdP9oi3dF86qdnJ1XZ4veBcjaNCKHy4C8pv8Sc=,tag:0Xs8KluW/Efa39Qaz5N4Iw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4UUFNVXJJSGpGTytzT015
            UFZYaWh6R3NzZzVlN3JFeUpmVEJwVVhsdGdJClRxQkgvVWlLMmFxQnhhOWR2MVZ2
            TkE5TXlnK2t5TTVsL2Q5elZyNGlnTG8KLS0tIHNvWmVvVnN2TzJodGNtcE5udk9M
            cXpjY05tMzhYaFdPQ2xSU1F6Vll2dGcKgb323hK7bXlGRakCvtkg71/8zvXX00o2
            5MPohcXDxd0nJkcaFe9ibdk3GGAaY8kEmZiiy5GRVxRG3ChTLJ7fJA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ukc0wt99g0jw038mzrx5g5r4cj7298mx3hdf2g9kqvtcme7vz5jsj0lxeq
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-12T14:49:47Z"
    mac: ENC[AES256_GCM,data:9LnPy6d94cGMvYT9qFeOuJp4blZa/6g/2coWkY5BHMBHdYGgdTC1PGypRAunDGKJqs6QJ7RjLeupda8CC+9BYB7HwwR4FEpf+OsueFjXPZ9muA4rfVHxmbaJMCfxsd9c7TJYmedLqHstHyeP1GUh8+FZZ4IoOSsVhY8qCQlBCHs=,iv:cF+5irWl/g4zm6WqFKCxMMHGO9+bLenAOF4ZYAWpsXg=,tag:Rze+WWJ0AKXt22+FR0a/lg==,type:str]
    version: 3.13.3
