# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: laneth-secrets
    namespace: flux-system
stringData:
    TIMEZONE: ENC[AES256_GCM,data:9f63EXfvVLv3WvUHKFey,iv:TLdn160hgKAuiBtY2c2M1jdaRWmseApQZ5qevXkfzGE=,tag:RFGAUfWGzyfPL4QTo5ZEYQ==,type:str]
    SECRET_PUBLIC_DOMAIN: ENC[AES256_GCM,data:tiivDsE70Bd9,iv:610gHC2O7GRHh5hR6/HR0c9tWGQm3eG3GcpLlsWI8nQ=,tag:UJAZDIjJTXMreir4zeu3xA==,type:str]
    SECRET_PRIVATE_DOMAIN: ENC[AES256_GCM,data:uQn4q/h6BG8erEHp,iv:UzMDbnPmLpyC3mfpMi0DGD1QWo3J4PWZQyN1aW2Ej7Y=,tag:YqXh7aN+ayNkb0XBxnsg2g==,type:str]
    SECRET_VPN_HOST: ENC[AES256_GCM,data:IGDNH8PlobOt5UClqh9aZCg=,iv:FDBF72E5fMg5xzxSpsSIRRUltpVQAYt1h+CHRRp+oTc=,tag:JVYARtF+qFDiWvXPliYpxw==,type:str]
    SECRET_VPN_IP: ENC[AES256_GCM,data:L3Gq01PjX8rwFwoxNjQ=,iv:N25493IRRqW4FaRC2Pi3Z3ZeDGRN1MeOL89tKhaKOpY=,tag:MgRjf5Hv8qncky+cYtthKQ==,type:str]
    SECRET_BACKUP_SERVER: ENC[AES256_GCM,data:f+8BD2mOXk6pmgKaWc6jAvFJuJ01WA==,iv:aIBm8TlyvtVC95Jh7DNODIV9wVDA3iXG5qil+c1nkzU=,tag:06gGZmN9SVmRdz+K0HyRPg==,type:str]
    SECRET_BACKUP_FOLDER: ENC[AES256_GCM,data:4jvWi3NzBqnqPs+Q0XoOrA==,iv:xxxRxdey3yLzoYRJazVK8Z7urHm1rTSbsiObVI1Bnmk=,tag:sRgmB0507hJTqYHG+pZRmA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ukc0wt99g0jw038mzrx5g5r4cj7298mx3hdf2g9kqvtcme7vz5jsj0lxeq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4UUFNVXJJSGpGTytzT015
            UFZYaWh6R3NzZzVlN3JFeUpmVEJwVVhsdGdJClRxQkgvVWlLMmFxQnhhOWR2MVZ2
            TkE5TXlnK2t5TTVsL2Q5elZyNGlnTG8KLS0tIHNvWmVvVnN2TzJodGNtcE5udk9M
            cXpjY05tMzhYaFdPQ2xSU1F6Vll2dGcKgb323hK7bXlGRakCvtkg71/8zvXX00o2
            5MPohcXDxd0nJkcaFe9ibdk3GGAaY8kEmZiiy5GRVxRG3ChTLJ7fJA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-21T17:18:43Z"
    mac: ENC[AES256_GCM,data:eyJwnrvHTe22RnPj7vZExAuAHvdxuXci9NeUizG7V4TUwj02HhJKTewemseTFXt99jBjHftZB0H0e9DGSa5Wv6OBEGdYgkH/3uRxXgVfCXt9Ut5K0VCQ/+S9W//rDqSQjQuaFfRosXZUsiurd9F/7XhBJdN5NC7Ncs9dPPvYPck=,iv:mEP5qsA4tWQdz+Kzc/E4UOeFcWT84/o7j1Ji60gSclc=,tag:j2q7F41GCg0JxD6w8kYQVA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
