---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-config-v3
  namespace: downloads
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
  storageClassName: zfs-block
