---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sonarr
  namespace: downloads
spec:
  interval: 15m
  chart:
    spec:
      chart: sonarr
      version: 16.2.3
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
  values:
    image:
      repository: ghcr.io/k8s-at-home/sonarr
      tag: v3.0.8.1507
    env:
      TZ: ${CONFIG_TIMEZONE}
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: "cloud-search"
        hosts:
          - host: &host "sonarr.${SECRET_INTERNAL_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    securityContext:
      runAsUser: 2000
      runAsGroup: 2000
    metrics:
      enabled: true
      serviceMonitor:
        interval: 3m
        scrapeTimeout: 1m
      prometheusRule:
        enabled: true
      exporter:
        image:
          repository: ghcr.io/onedr0p/exportarr
          tag: v1.0.0
        env:
          port: 9794
          additionalMetrics: true
          unknownQueueItems: true
    podAnnotations:
      backup.velero.io/backup-volumes: config
    persistence:
      config:
        enabled: true
        existingClaim: sonarr-config-v3
      media:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "${SECRET_MEDIA_SERVER}"
            path: /media
        mountPath: /media
      backup:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "${SECRET_BACKUP_SERVER}"
            path: /backup/data/app/sonarr
        mountPath: /config/Backups
        readOnly: false
    resources:
      requests:
        memory: 250Mi
        cpu: 250m
      limits:
        memory: 2000Mi
