---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: recyclarr
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.3.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    initContainers:
      01-init-config:
        image: public.ecr.aws/docker/library/busybox:latest
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh", "-c", "cp /tmp/config/recyclarr.yml /config/recyclarr.yml"]
        volumeMounts:
          - { name: config-file, mountPath: /tmp/config }
          - { name: config, mountPath: /config }
    controller:
      annotations:
        reloader.stakater.com/auto: "true"
    image:
      repository: ghcr.io/recyclarr/recyclarr
      tag: edge@sha256:926f86e2572efd8db0586f839ec8fcdc085c561f4b913fac43d6047720c067c3
    env:
      TZ: ${TIMEZONE}
    envFrom:
      - secretRef:
          name: recyclarr
    service:
      main:
        enabled: false
    podSecurityContext:
      runAsUser: 1022
      runAsGroup: 1022
      fsGroup: 1022
      fsGroupChangePolicy: OnRootMismatch
    persistence:
      config:
        enabled: true
        mountPath: /config
        existingClaim: recyclarr-config-v1
      config-file:
        enabled: true
        type: configMap
        name: recyclarr
        mountPath: "-"
    resources:
      requests:
        cpu: 10m
        memory: 50Mi
      limits:
        memory: 200Mi
