---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: overseerr-config-v4
  namespace: downloads
  labels:
    snapshot.home.arpa/enabled: "true"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ceph-block
