---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: overseerr
  namespace: downloads
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.2.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    image:
      repository: ghcr.io/sct/overseerr
      tag: 1.31.0
    controller:
      labels:
        setGateway: "true"
    env:
      TZ: ${TIMEZONE}
      LOG_LEVEL: "info"
      PORT: &port 80
    service:
      main:
        ports:
          http:
            port: *port
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          external-dns.home.arpa/enabled: "true"
          hajimari.io/enable: "true"
          hajimari.io/icon: "television-classic"
        hosts:
          - host: &host "requests.${SECRET_PUBLIC_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
            secretName: tls.overseerr
      internal:
        enabled: true
        ingressClassName: nginx
        hosts:
          - host: &hosti requests.${SECRET_INTERNAL_DOMAIN}
            paths:
              - path: /
        tls:
          - hosts:
              - *hosti
    podSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
      fsGroupChangePolicy: OnRootMismatch
    persistence:
      config:
        enabled: true
        existingClaim: overseerr-config-v4
        mountPath: /app/config
    resources:
      requests:
        cpu: 250m
        memory: 250Mi
      limits:
        memory: 500Mi
