---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: overseerr
  namespace: downloads
spec:
  interval: 15m
  chart:
    spec:
      chart: overseerr
      version: 5.3.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
  values:
    image:
      repository: ghcr.io/sct/overseerr
      tag: 1.29.1
    env:
      TZ: ${CONFIG_TIMEZONE}
      LOG_LEVEL: "info"
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          external-dns.alpha.kubernetes.io/target: "gw.${SECRET_PUBLIC_DOMAIN}"
          external-dns/is-public: "true"
          hajimari.io/enable: "true"
          hajimari.io/icon: "television-classic"
        hosts:
          - host: &host "requests.${SECRET_PUBLIC_DOMAIN}"
            paths:
              - path: /
        tls:
          - hosts:
              - *host
            secretName: tls.overseerr
      internal:
        enabled: true
        ingressClassName: "traefik"
        hosts:
          - host: &hosti requests.${SECRET_INTERNAL_DOMAIN}
            paths:
              - path: /
        tls:
          - hosts:
              - *hosti
    podAnnotations:
      backup.velero.io/backup-volumes: config
    persistence:
      config:
        enabled: true
        existingClaim: overseerr-config-v3
        mountPath: /app/config
    resources:
      requests:
        memory: 250Mi
        cpu: 250m
      limits:
        memory: 750Mi
