---
name: "HelmRelease Diff"

on:
  pull_request:
    branches: ["main"]
    paths: ["kubernetes/**/helmrelease.yaml"]

env:
  HELMREPOSITORY_DIR: ./kubernetes/flux/repositories/helm

jobs:
  changed-files:
    name: Detect File Changes
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@b2d17f51244a144849c6b37a3a6791b98a51d86f # v35.9.2
        with:
          json: true
          files: |
            kubernetes/**/helmrelease.yaml

      - id: set-matrix
        run: echo "matrix={\"file\":${{ steps.changed-files.outputs.all_changed_files }}}" >> "${GITHUB_OUTPUT}"

  diff:
    name: Diff on Helm Releases
    runs-on: ubuntu-latest
    needs: [changed-files]
    strategy:
      matrix: ${{ fromJSON(needs.changed-files.outputs.matrix) }}
    steps:
      - name: Checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2

      - name: Checkout default branch
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
        with:
          ref: ${{ github.event.repository.default_branch }}
          path: default

      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Setup Tools
        run: |
          brew install helm homeport/tap/dyff kustomize yq

      - name: Template out Helm values on pull request
        id: pull-request
        run: |
          releaseName=$(yq eval '.metadata.name' "${{ matrix.file }}")
          manifests=$(npx zx ./.github/scripts/helmrelease-diff.mjs \
            --helm-release-name "${releaseName}" \
            --kustomize-base-dir "$(dirname "${{ matrix.file }}")" \
            --helm-repository-dir ${{ env.HELMREPOSITORY_DIR }})
          echo "file=${manifests}" >> "${GITHUB_OUTPUT}"

      - name: Template out Helm values on default branch
        id: default
        working-directory: default
        run: |
          releaseName=$(yq eval '.metadata.name' "${{ matrix.file }}")
          manifests=$(npx zx ../.github/scripts/helmrelease-diff.mjs \
            --helm-release-name "${releaseName}" \
            --kustomize-base-dir "$(dirname "${{ matrix.file }}")" \
            --helm-repository-dir ${{ env.HELMREPOSITORY_DIR }})
          echo "file=${manifests}" >> "${GITHUB_OUTPUT}"

      - name: Diff
        id: diff
        run: |
          diff=$(dyff between --color off --truecolor off --omit-header \
            ${{ steps.default.outputs.file }} \
            ${{ steps.pull-request.outputs.file }} | tail -n +2)
          echo "diff<<EOF" >> "${GITHUB_OUTPUT}"
          echo "${diff}" >> "${GITHUB_OUTPUT}"
          echo "EOF" >> "${GITHUB_OUTPUT}"

      - name: Find Comment
        uses: peter-evans/find-comment@a54c31d7fa095754bfef525c0c8e5e5674c4b4b1 # v2.4.0
        id: find-comment
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body-includes: ${{ matrix.file }}

      - name: Create or update comment
        uses: peter-evans/create-or-update-comment@ca08ebd5dc95aa0cd97021e9708fcd6b87138c9b # v3.0.1
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          comment-id: ${{ steps.find-comment.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Helm Release: `${{ matrix.file }}`

            ```
            ${{ steps.diff.outputs.diff }}
            ```
          edit-mode: replace
