---
name: "HelmRelease Diff"

on:
  pull_request:
    branches: ["main"]
    paths: ["kubernetes/**/helmrelease.yaml"]

env:
  HELMREPOSITORY_DIR: ./kubernetes/flux/repositories/helm

jobs:
  changed-files:
    name: Detect File Changes
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@fea790cb660e33aef4bdf07304e28fedd77dfa13 # v39.2.4
        with:
          json: true
          files: |
            kubernetes/**/helmrelease.yaml

      - id: set-matrix
        run: echo "matrix={\"file\":${{ steps.changed-files.outputs.all_changed_files }}}" >> "${GITHUB_OUTPUT}"

  diff:
    name: Diff on Helm Releases
    runs-on: ubuntu-latest
    needs: [changed-files]
    strategy:
      matrix: ${{ fromJSON(needs.changed-files.outputs.matrix) }}
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Checkout default branch
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          ref: ${{ github.event.repository.default_branch }}
          path: default

      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Setup Tools
        run: |
          brew install helm homeport/tap/dyff kustomize yq

      - name: Template out Helm values on pull request
        id: pull-request
        run: |
          releaseName=$(yq eval '.metadata.name' "${{ matrix.file }}")
          manifests=$(npx zx ./.github/scripts/helmrelease-diff.mjs \
            --helm-release-name "${releaseName}" \
            --kustomize-base-dir "$(dirname "${{ matrix.file }}")" \
            --helm-repository-dir ${{ env.HELMREPOSITORY_DIR }})
          echo "file=${manifests}" >> "${GITHUB_OUTPUT}"

      - name: Template out Helm values on default branch
        id: default
        working-directory: default
        run: |
          releaseName=$(yq eval '.metadata.name' "${{ matrix.file }}")
          manifests=$(npx zx ../.github/scripts/helmrelease-diff.mjs \
            --helm-release-name "${releaseName}" \
            --kustomize-base-dir "$(dirname "${{ matrix.file }}")" \
            --helm-repository-dir ${{ env.HELMREPOSITORY_DIR }})
          echo "file=${manifests}" >> "${GITHUB_OUTPUT}"

      - name: Diff
        id: diff
        run: |
          diff=$(dyff between --color off --truecolor off --omit-header \
            ${{ steps.default.outputs.file }} \
            ${{ steps.pull-request.outputs.file }} | tail -n +2)
          echo "diff<<EOF" >> "${GITHUB_OUTPUT}"
          echo "${diff}" >> "${GITHUB_OUTPUT}"
          echo "EOF" >> "${GITHUB_OUTPUT}"

      - name: Find Comment
        uses: peter-evans/find-comment@a54c31d7fa095754bfef525c0c8e5e5674c4b4b1 # v2.4.0
        id: find-comment
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body-includes: ${{ matrix.file }}

      - name: Create or update comment
        uses: peter-evans/create-or-update-comment@23ff15729ef2fc348714a3bb66d2f655ca9066f2 # v3.1.0
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          comment-id: ${{ steps.find-comment.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Helm Release: `${{ matrix.file }}`

            ```
            ${{ steps.diff.outputs.diff }}
            ```
          edit-mode: replace
